# Generated by Django 3.1.4 on 2020-12-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
