# Generated by Django 3.1.4 on 2020-12-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapi', '0002_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
